$ANSIBLE_VAULT;1.1;AES256
38613732633530656438663966366530363336396263356530636664393831376430383534663566
6634623262383333373362383538633561303537376466610a626633353936346232343831636132
62656131646161623262376231363062353732313136396635393330353233313035666562346635
6163623835623631310a336137633030353065306261633134626630336533313039666161663466
32343338366563316164643063656130303264363237346439346334363765366462623236343435
37643639626534616131613534333163653631383964323235316363383331313434383637663333
32323462663538396435373338323735323864366362363363326331303734663536636164623431
61323937633062353761663839323139313034356466656165373363653166646239303332313537
6335
