$ANSIBLE_VAULT;1.1;AES256
34393463383634356564623236353561333762656536666237626436326439633733353534613539
3736323633653530356362643337653862656366316530610a373530316162663437333638336566
66353332346666313535376136666532616564326566313232376262656461303765643032326133
6134393362373739300a373061383065343139323835666262333266643963616264643663373330
39343862373930306634353436393232663033333963636463376134633130343637
