$ANSIBLE_VAULT;1.1;AES256
65643530376134303463393866363632316635343232633333396466333161653631326465313762
3561343631373335363532366562653639306162326363340a633762326364626637346135303039
66613433306666333132393232376366373165363961636239363235303236623664366633343766
3835653433353933630a333536333832373637343435653364333562316362636663613239636665
61613864383864363838613337396333326534326234323738386530313565343639363733663939
34303938316133306666353366623437343831643731626130613337663633303465373335396230
62646637373838383635313236396531633663393436303539653435653963353339633966386331
36633561633562643531303839616635333232333033653437623162363530653862303363336436
6130
